[Dialogs]
UserInfo=0
FeatureInfo1=1
SingleDirectory=1
InstallationType=0
FeatureTree=0
License=0
License2=1
NICertificate=0
WinFastStartup=1
ConfirmStart=1
End=1

[Distribution]
Title=1
GUID={81850D00-E361-4710-976B-31FE2E74C67D}
PackageGUID={4FCE8C1A-4CF4-462D-82E7-FEF17D427CAB}
Version=1.0.0
IDPath=nidist.id
Has64bitPart=1

[EndDialog]
Readme=5;30,50,330,150;static

[Files]
License2TextFile0009=NI;license\NI Released License Agreement - English.rtf
License2TextFile0010=NI;license\NI Released License Agreement - Spanish.rtf
License2TextFile0016=NI;license\NI Released License Agreement - Italian.rtf
License2TextFile0007=NI;license\NI Released License Agreement - German.rtf
License2TextFile0012=NI;license\NI Released License Agreement - French.rtf
License2TextFile0017=NI;license\NI Released License Agreement - Japanese.rtf
License2TextFile0018=NI;license\NI Released License Agreement - Korean.rtf
License2TextFile2052=NI;license\NI Released License Agreement - Simplified Chinese.rtf

[Graphics]
TopBar=IDB_TOPSTRIP,IDB_LARGETOPSTRIP
FullScreen=IDB_FULLSCREEN,IDB_LARGEFULLSCREEN

[InitProgress]
left=55
top=165
right=340
bottom=179
red=206
green=203
blue=173

[InstallLevels]
Default=100

[Localization]
Languages=9
ForceLanguage=9
CustomRes0009=supportfiles\customResource0009.dll
StandardLangXfm0007=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0007.mst
StandardLangXfm0012=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0012.mst
StandardLangXfm0017=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0017.mst
StandardLangXfm0018=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans0018.mst
StandardLangXfm2052=supportfiles\nistdtransbase.mst;supportfiles\nistdtrans2052.mst

[Merged]
Path=supportfiles\merged.cab

[OS]
VersionNTMin=5,1,2600,3,0
VersionNTMax=

[Settings]
WelcomeAutoAdvance=1

[SingleDirectoryDialog]
DirText1=4
DirText2=7
Dir1=INSTALLDIR.MDF100
Dir1EditLabel=8
Dir2=NIDIR
Dir2EditLabel=9

[WinFastStartupDialog]
CheckboxDefaultState=1

[Strings]
WelcomeTitle=2;15,20,260,45
WelcomeText=3;15,55,260,115

[Utilities]
UpgradeManagerPostProcessor=supportfiles\niPie.exe

[Parts]
CVI_RTE.msi=
CVI_RTE64.msi=
CVI_Analysis.msi=
CVI_Analysis64.msi=
CVI_TDMS.msi=
CVI_TDMS64.msi=
CVI_NetworkVariable.msi=
CVI_NetworkVariable64.msi=
CVI_LowLevelDriverOriginal.msi=
CVI_LowLevelDriverUpdated.msi=
CVI_RTEUpdated.msi=
MetaUninstaller.msi=
MDFSupport.msi=
EulaDepot.msi=
Remote_Configuration.msi=
Remote_Configuration64.msi=
VC2005MSMs_x86.msi=
VC2005MSMs_x64.msi=
VC2008MSMs_x86.msi=
VC2008MSMs_x64.msi=
VC2010MSMs_x86.msi=
VC2010MSMs_x64.msi=
VC2005MSMs_Redist.msi=
VC2008MSMs_Redist.msi=
VC2010MSMs_Redist.msi=
ni_mesa.msi=
ni_mesa64.msi=
activex.msi=
activex64.msi=
mkl.msi=
mkl64.msi=
tdms.msi=
tdms64.msi=
logos.msi=
logos64.msi=
KillBit.msi=
KillBit64.msi=
LogosXT.msi=
LogosXT64.msi=
USB_DAQ_V52_TEST.msi=
[CVI_RTE.msi]
Path=bin\p21\CVI_RTE.msi
Volume=1
ProductCode={51D4DD2F-1F7B-45CF-B0EB-CCBE28F7F426}
ProductId={51D4DD2F-1F7B-45CF-B0EB-CCBE28F7F426}
[CVI_RTE64.msi]
Path=bin\p21\CVI_RTE64.msi
Volume=1
ProductCode={6E36027F-5387-416C-8D48-D198C9974E6E}
[CVI_Analysis.msi]
Path=bin\p14\CVI_Analysis.msi
Volume=1
ProductCode={A8E6A3B8-9F9F-49D6-8234-B26A2F286672}
ProductId={A8E6A3B8-9F9F-49D6-8234-B26A2F286672}
[CVI_Analysis64.msi]
Path=bin\p14\CVI_Analysis64.msi
Volume=1
ProductCode={75068D66-68A2-457F-A338-FDFCFD5AC899}
[CVI_TDMS.msi]
Path=bin\p6\CVI_TDMS.msi
Volume=1
ProductCode={607FDA78-F3F5-46D4-8CC8-08456F18F288}
ProductId={607FDA78-F3F5-46D4-8CC8-08456F18F288}
[CVI_TDMS64.msi]
Path=bin\p6\CVI_TDMS64.msi
Volume=1
ProductCode={FD75B7E9-2C12-44B0-8C24-9BF22AC551F0}
[CVI_NetworkVariable.msi]
Path=bin\p10\CVI_NetworkVariable.msi
Volume=1
ProductCode={E1FCA1A6-C420-4252-8C42-BF774A737A53}
ProductId={E1FCA1A6-C420-4252-8C42-BF774A737A53}
[CVI_NetworkVariable64.msi]
Path=bin\p10\CVI_NetworkVariable64.msi
Volume=1
ProductCode={5012CE95-BC61-44AC-A212-B0D05F8A8896}
[CVI_LowLevelDriverOriginal.msi]
Path=bin\p5\CVI_LowLevelDriverOriginal.msi
Volume=1
ProductCode={70400242-737B-4BB1-A951-4FACC011A5D9}
ProductId={70400242-737B-4BB1-A951-4FACC011A5D9}
[CVI_LowLevelDriverUpdated.msi]
Path=bin\p5\CVI_LowLevelDriverUpdated.msi
Volume=1
ProductCode={0DEEF8A0-A14B-4058-96E2-59B00C581A42}
[CVI_RTEUpdated.msi]
Path=bin\p17\CVI_RTEUpdated.msi
Volume=1
ProductCode={C6F3B186-7943-476B-931E-7AC8FADB7563}
ProductId={C6F3B186-7943-476B-931E-7AC8FADB7563}
[MetaUninstaller.msi]
Path=bin\p0\MU\MetaUninstaller.msi
Volume=1
ProductCode={0BA91512-3CC9-476F-9EAC-1D88BF82105E}
ProductId={0BA91512-3CC9-476F-9EAC-1D88BF82105E}
[MDFSupport.msi]
Path=bin\p19\MDF\MDFSupport.msi
Volume=1
ProductCode={A32D7AC5-9C70-4F85-AB68-1D276599A6EA}
ProductId={A32D7AC5-9C70-4F85-AB68-1D276599A6EA}
[EulaDepot.msi]
Path=bin\p19\MDF\EulaDepot.msi
Volume=1
ProductCode={1C7DB297-FD1E-448E-9388-A32A2C68D306}
[Remote_Configuration.msi]
Path=bin\p7\Remote_Configuration.msi
Volume=1
ProductCode={C1272805-6A7E-4654-B419-896BECE31C12}
ProductId={C1272805-6A7E-4654-B419-896BECE31C12}
[Remote_Configuration64.msi]
Path=bin\p7\Remote_Configuration64.msi
Volume=1
ProductCode={F1E88BA0-AAAD-4751-971C-B66ECD8403A4}
[VC2005MSMs_x86.msi]
Path=bin\p1\VC2005MSMs\VC2005MSMs_x86.msi
Volume=1
ProductCode={4B877FC6-F44C-4B39-B0B6-CE15ADC63997}
ProductId={4B877FC6-F44C-4B39-B0B6-CE15ADC63997}
[VC2005MSMs_x64.msi]
Path=bin\p1\VC2005MSMs\VC2005MSMs_x64.msi
Volume=1
ProductCode={E3E3E625-8F74-44CE-A6D2-C31CB43DA23D}
[VC2008MSMs_x86.msi]
Path=bin\p3\VC2008MSMs\VC2008MSMs_x86.msi
Volume=1
ProductCode={E84997A1-4D6F-4C0B-B60D-F85B360D2666}
ProductId={E84997A1-4D6F-4C0B-B60D-F85B360D2666}
[VC2008MSMs_x64.msi]
Path=bin\p3\VC2008MSMs\VC2008MSMs_x64.msi
Volume=1
ProductCode={07E00E94-7A78-40FA-9BEF-71C190E98041}
[VC2010MSMs_x86.msi]
Path=bin\p2\VC2010MSMs_x86.msi
Volume=1
ProductCode={F2273FA7-117C-43D7-BD59-00B025535442}
ProductId={F2273FA7-117C-43D7-BD59-00B025535442}
[VC2010MSMs_x64.msi]
Path=bin\p2\VC2010MSMs_x64.msi
Volume=1
ProductCode={AFC5A844-CA3A-4566-89E7-3E24E6AFF9A3}
[VC2005MSMs_Redist.msi]
Path=bin\p13\VC2005MSMs_Redist.msi
Volume=1
ProductCode={BD5DF99A-2CD3-4349-BB98-C7DFA1F0EA04}
ProductId={BD5DF99A-2CD3-4349-BB98-C7DFA1F0EA04}
[VC2008MSMs_Redist.msi]
Path=bin\p16\VC2008MSMs_Redist.msi
Volume=1
ProductCode={08505CC2-EA7F-4818-9C45-B74EDA7227F8}
ProductId={08505CC2-EA7F-4818-9C45-B74EDA7227F8}
[VC2010MSMs_Redist.msi]
Path=bin\p18\VC2010MSMs_Redist.msi
Volume=1
ProductCode={1C3B75E1-DA30-404C-B2C2-9BD31AB64909}
ProductId={1C3B75E1-DA30-404C-B2C2-9BD31AB64909}
[ni_mesa.msi]
Path=bin\p8\ni_mesa.msi
Volume=1
ProductCode={3AA5FCD0-8215-4604-920C-BC87CE1D843B}
ProductId={3AA5FCD0-8215-4604-920C-BC87CE1D843B}
[ni_mesa64.msi]
Path=bin\p8\ni_mesa64.msi
Volume=1
ProductCode={7716F0A8-AFEF-4C22-9A10-4D5BDCD6471D}
[activex.msi]
Path=bin\p11\activex.msi
Volume=1
ProductCode={4C146083-2C71-4C64-A4AD-5E340E177E63}
ProductId={4C146083-2C71-4C64-A4AD-5E340E177E63}
LangXfm0007=bin\p11\activ32_deu.mst
LangXfm0012=bin\p11\activ32_fra.mst
LangXfm0017=bin\p11\activ32_jpn.mst
LangXfm0018=bin\p11\activ32_kor.mst
LangXfm2052=bin\p11\activ32_chs.mst
[activex64.msi]
Path=bin\p11\activex64.msi
Volume=1
ProductCode={86F88524-6AF8-4D10-9F3C-AFB0DA2A3F39}
LangXfm0007=bin\p11\activ64_deu.mst
LangXfm0012=bin\p11\activ64_fra.mst
LangXfm0017=bin\p11\activ64_jpn.mst
LangXfm0018=bin\p11\activ64_kor.mst
LangXfm2052=bin\p11\activ64_chs.mst
[mkl.msi]
Path=bin\p15\mkl.msi
Volume=1
ProductCode={4C16E76C-7A4D-48E7-9E5E-B76B357C014E}
ProductId={4C16E76C-7A4D-48E7-9E5E-B76B357C014E}
LangXfm0007=bin\p15\MKL2012_deu.mst
LangXfm0012=bin\p15\MKL2012_fra.mst
LangXfm0017=bin\p15\MKL2012_jpn.mst
LangXfm0018=bin\p15\MKL2012_kor.mst
LangXfm2052=bin\p15\MKL2012_chs.mst
[mkl64.msi]
Path=bin\p15\mkl64.msi
Volume=1
ProductCode={E3EB4126-0930-4926-B135-1F85452E7975}
LangXfm0007=bin\p15\MKL2000_deu.mst
LangXfm0012=bin\p15\MKL2000_fra.mst
LangXfm0017=bin\p15\MKL2000_jpn.mst
LangXfm0018=bin\p15\MKL2000_kor.mst
LangXfm2052=bin\p15\MKL2000_chs.mst
[tdms.msi]
Path=bin\p12\tdms.msi
Volume=1
ProductCode={27367777-A95D-4014-B73B-18D4838E54A4}
ProductId={27367777-A95D-4014-B73B-18D4838E54A4}
LangXfm0007=bin\p12\tdms_deu.mst
LangXfm0012=bin\p12\tdms_fra.mst
LangXfm0017=bin\p12\tdms_jpn.mst
LangXfm0018=bin\p12\tdms_kor.mst
LangXfm2052=bin\p12\tdms_chs.mst
[tdms64.msi]
Path=bin\p12\tdms64.msi
Volume=1
ProductCode={3ABCF186-64DE-439C-8B66-CC31B8513D8C}
LangXfm0007=bin\p12\tdms64_deu.mst
LangXfm0012=bin\p12\tdms64_fra.mst
LangXfm0017=bin\p12\tdms64_jpn.mst
LangXfm0018=bin\p12\tdms64_kor.mst
LangXfm2052=bin\p12\tdms64_chs.mst
[logos.msi]
Path=bin\p20\logos.msi
Volume=1
ProductCode={CA533BA0-E6F9-4349-B0EC-ABDEB0481E77}
ProductId={CA533BA0-E6F9-4349-B0EC-ABDEB0481E77}
LangXfm0007=bin\p20\logos_deu.mst
LangXfm0012=bin\p20\logos_fra.mst
LangXfm0017=bin\p20\logos_jpn.mst
LangXfm0018=bin\p20\logos_kor.mst
LangXfm2052=bin\p20\logos_chs.mst
[logos64.msi]
Path=bin\p20\logos64.msi
Volume=1
ProductCode={B2149E16-A01C-458E-A6E5-B9DC96EAD1AA}
LangXfm0007=bin\p20\logos64_deu.mst
LangXfm0012=bin\p20\logos64_fra.mst
LangXfm0017=bin\p20\logos64_jpn.mst
LangXfm0018=bin\p20\logos64_kor.mst
LangXfm2052=bin\p20\logos64_chs.mst
[KillBit.msi]
Path=bin\p4\KillBit.msi
Volume=1
ProductCode={20124E21-206B-485F-838F-14BB88161045}
ProductId={20124E21-206B-485F-838F-14BB88161045}
[KillBit64.msi]
Path=bin\p4\KillBit64.msi
Volume=1
ProductCode={4A78D9E6-D349-4CCA-9295-45B12BE5BC6C}
[LogosXT.msi]
Path=bin\p9\LogosXT.msi
Volume=1
ProductCode={A05EFB3F-19E2-4F9E-8380-BE095CCF0BE4}
ProductId={A05EFB3F-19E2-4F9E-8380-BE095CCF0BE4}
[LogosXT64.msi]
Path=bin\p9\LogosXT64.msi
Volume=1
ProductCode={A3154334-4692-449E-8836-3CCD28D0B1D7}
[USB_DAQ_V52_TEST.msi]
Path=bin\dp\USB_DAQ_V52_TEST.msi
Volume=1
ProductCode={0810ABC1-C8BF-413A-9964-7108C3053A44}
ProductId={0810ABC1-C8BF-413A-9964-7108C3053A44}
[LicenseTypes]
LicenseType2=NIStandardReleased
LicenseType3=Apache20
LicenseType4=Libtiff
LicenseType5=LGPL
LicenseType6=Mesa
LicenseType7=Strtod
LicenseType8=UPX
LicenseType9=wxWindows
LicenseType10=zlib
[LicenseType2]
IsDisplayedAlone=0
IsThirdParty=0
IsHideInMetaSuite=0
[LicenseType3]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType4]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType5]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType6]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType7]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType8]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType9]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[LicenseType10]
IsDisplayedAlone=0
IsThirdParty=1
IsHideInMetaSuite=0
[SilentInstallRequirements]
MustAcceptLicenses=1
[MDF]
MDFVersion=3.2.0.356
HasPatchSupport=1
DevPartSection=USB_DAQ_V52_TEST.msi
